import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Cloud, Moon, Sun, Image as ImageIcon, Video, Folder, Star, Trash2, Share2, Settings, LogOut, Upload, Search, ShieldCheck, HardDrive, Plus, Menu, X, ArrowLeft, Download, MoreVertical, RefreshCw, Grid2X2, List, User, Palette, FolderPlus, Album, Copy, Check, ExternalLink, Lock, KeyRound, Save, Eye, EyeOff } from 'lucide-react'
import { supabase, supabaseConfigured } from './supabase'
import './styles.css'

const TB = 1024 ** 4
const BG_THEMES = [
  { id:'aurora', name:'Aurora', className:'bg-aurora' },
  { id:'ocean', name:'Ocean', className:'bg-ocean' },
  { id:'sunset', name:'Sunset', className:'bg-sunset' },
  { id:'forest', name:'Forest', className:'bg-forest' },
  { id:'midnight', name:'Midnight', className:'bg-midnight' },
]

function App(){
  const [session,setSession]=useState(null), [theme,setTheme]=useState(localStorage.getItem('my-cloud-theme')||'light')
  const [background,setBackground]=useState(localStorage.getItem('my-cloud-bg')||'aurora')
  const [page,setPage]=useState('home'), [mobileOpen,setMobileOpen]=useState(false), [notice,setNotice]=useState('')
  const [files,setFiles]=useState([]), [folders,setFolders]=useState([]), [albums,setAlbums]=useState([]), [profile,setProfile]=useState(null)
  const [loading,setLoading]=useState(false), [uploading,setUploading]=useState(false), [authMode,setAuthMode]=useState('landing')
  const [currentFolder,setCurrentFolder]=useState(null), [selectedAlbum,setSelectedAlbum]=useState(null), [search,setSearch]=useState('')
  useEffect(()=>{ document.documentElement.dataset.theme=theme; localStorage.setItem('my-cloud-theme',theme) },[theme])
  useEffect(()=>{ document.documentElement.dataset.bg=background; localStorage.setItem('my-cloud-bg',background) },[background])
  useEffect(()=>{ if(!supabase)return; supabase.auth.getSession().then(({data})=>setSession(data.session)); const {data:l}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return()=>l.subscription.unsubscribe() },[])
  useEffect(()=>{ if(session) loadAll() },[session,page,currentFolder,selectedAlbum])
  async function loadAll(){ if(!supabase||!session)return; setLoading(true); try{
    const [f,fo,a,p]=await Promise.all([
      supabase.from('files').select('*').eq('owner_id',session.user.id).order('created_at',{ascending:false}),
      supabase.from('folders').select('*').eq('owner_id',session.user.id).order('name'),
      supabase.from('albums').select('*').eq('owner_id',session.user.id).order('name'),
      supabase.from('profiles').select('*').eq('id',session.user.id).maybeSingle()
    ])
    if(f.error)throw f.error; setFiles(f.data||[]); setFolders(fo.data||[]); setAlbums(a.data||[]); setProfile(p.data||null)
  }catch(e){setNotice(e.message||'Could not load your cloud.')}finally{setLoading(false)} }
  async function google(){ if(!supabaseConfigured)return setNotice('Connect Supabase first.'); const {error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:window.location.origin}}); if(error)setNotice(error.message) }
  async function signOut(){await supabase?.auth.signOut();setPage('home')}
  async function uploadFiles(list){ if(!supabase||!session||!list?.length)return; setUploading(true); try{ for(const file of Array.from(list)){ const {data:q,error:qe}=await supabase.rpc('get_storage_usage'); if(qe)throw qe; if(Number(q||0)+file.size>TB)throw new Error('This upload would exceed your 1 TB quota.'); const safe=file.name.replace(/[^\w.\- ()]/g,'_'); const path=`${session.user.id}/${crypto.randomUUID()}-${safe}`; const {error:se}=await supabase.storage.from('user-files').upload(path,file,{cacheControl:'3600',upsert:false}); if(se)throw se; const {error:de}=await supabase.from('files').insert({owner_id:session.user.id,name:file.name,storage_path:path,mime_type:file.type||'application/octet-stream',size_bytes:file.size,kind:file.type.startsWith('image/')?'photo':file.type.startsWith('video/')?'video':'file',folder_id:currentFolder?.id||null,album_id:selectedAlbum?.id||null}); if(de){await supabase.storage.from('user-files').remove([path]);throw de} } setNotice('Upload complete.'); await loadAll() }catch(e){setNotice(e.message||'Upload failed.')}finally{setUploading(false)} }
  async function createFolder(name,parent=currentFolder?.id||null){ const n=name.trim(); if(!n)return; const {error}=await supabase.from('folders').insert({owner_id:session.user.id,name:n,parent_id:parent}); if(error)setNotice(error.message); else{setNotice('Folder created.');loadAll()} }
  async function renameFolder(folder){const n=prompt('New folder name',folder.name);if(!n?.trim())return;const {error}=await supabase.from('folders').update({name:n.trim()}).eq('id',folder.id).eq('owner_id',session.user.id);if(error)setNotice(error.message);else loadAll()}
  async function deleteFolder(folder){if(!confirm(`Delete folder “${folder.name}”? Files inside are kept.`))return;const {error}=await supabase.from('folders').delete().eq('id',folder.id).eq('owner_id',session.user.id);if(error)setNotice(error.message);else{if(currentFolder?.id===folder.id)setCurrentFolder(null);loadAll()}}
  async function createAlbum(name){const n=name.trim();if(!n)return;const {error}=await supabase.from('albums').insert({owner_id:session.user.id,name:n});if(error)setNotice(error.message);else{setNotice('Album created.');loadAll()}}
  async function renameAlbum(album){const n=prompt('New album name',album.name);if(!n?.trim())return;const {error}=await supabase.from('albums').update({name:n.trim()}).eq('id',album.id).eq('owner_id',session.user.id);if(error)setNotice(error.message);else loadAll()}
  async function deleteAlbum(album){if(!confirm(`Delete album “${album.name}”? Files are kept.`))return;const {error}=await supabase.from('albums').delete().eq('id',album.id).eq('owner_id',session.user.id);if(error)setNotice(error.message);else{setSelectedAlbum(null);loadAll()}}
  async function toggleFavorite(item){const {error}=await supabase.from('files').update({is_favorite:!item.is_favorite}).eq('id',item.id).eq('owner_id',session.user.id);if(error)setNotice(error.message);else loadAll()}
  async function moveToFolder(item,folderId){const {error}=await supabase.from('files').update({folder_id:folderId||null}).eq('id',item.id).eq('owner_id',session.user.id);if(error)setNotice(error.message);else loadAll()}
  async function trash(item){const {error}=await supabase.from('files').update({is_trashed:true,trashed_at:new Date().toISOString()}).eq('id',item.id).eq('owner_id',session.user.id);if(error)setNotice(error.message);else loadAll()}
  async function restore(item){const {error}=await supabase.from('files').update({is_trashed:false,trashed_at:null}).eq('id',item.id).eq('owner_id',session.user.id);if(error)setNotice(error.message);else loadAll()}
  async function forever(item){if(!confirm(`Permanently delete “${item.name}”?`))return;await supabase.storage.from('user-files').remove([item.storage_path]);const {error}=await supabase.from('files').delete().eq('id',item.id).eq('owner_id',session.user.id);if(error)setNotice(error.message);else loadAll()}
  async function download(item){try{setNotice('Preparing download…');const {data,error}=await supabase.storage.from('user-files').download(item.storage_path);if(error)throw error;const u=URL.createObjectURL(data),a=document.createElement('a');a.href=u;a.download=item.name;a.style.display='none';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);setNotice('Download started.')}catch(e){setNotice(e.message||'Download failed.')}}
  async function share(item){try{const {data,error}=await supabase.storage.from('user-files').createSignedUrl(item.storage_path,3600);if(error)throw error; await navigator.clipboard?.writeText(data.signedUrl);setNotice('Share link copied. It is valid for 1 hour.')}catch(e){setNotice(e.message||'Sharing failed.')}}
  async function saveProfile(values){const {error}=await supabase.from('profiles').update({display_name:values.display_name,avatar_url:values.avatar_url}).eq('id',session.user.id);if(error)setNotice(error.message);else{setNotice('Profile saved.');loadAll()}}
  async function changePassword(password){const {error}=await supabase.auth.updateUser({password});if(error)setNotice(error.message);else setNotice('Password updated.')}
  if(!session)return <Landing theme={theme} setTheme={setTheme} onGoogle={google} authMode={authMode} setAuthMode={setAuthMode} notice={notice} />
  return <Dashboard {...{session,theme,setTheme,background,setBackground,page,setPage,mobileOpen,setMobileOpen,files,folders,albums,profile,loading,uploading,notice,setNotice,currentFolder,setCurrentFolder,selectedAlbum,setSelectedAlbum,search,setSearch,uploadFiles,createFolder,renameFolder,deleteFolder,createAlbum,renameAlbum,deleteAlbum,toggleFavorite,moveToFolder,trash,restore,forever,download,share,saveProfile,changePassword,signOut}} />
}

function Landing(p){return <div className="landing"><header className="topbar"><Brand/><div className="top-actions"><ThemeToggle {...p}/><button className="ghost-btn" onClick={()=>p.setAuthMode('signin')}>Sign in</button></div></header><main className="landing-main"><section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="dot"/>YOUR PERSONAL CLOUD</div><h1>Your memories.<br/><span>Your files.</span><br/>Your cloud.</h1><p className="hero-text">Keep photos, videos and important files organized in a private cloud you can access from any device.</p><div className="hero-actions"><button className="primary-btn" onClick={p.onGoogle}><span className="google">G</span>Continue with Google</button><button className="secondary-btn" onClick={()=>p.setAuthMode('signin')}>✉ Continue with Email</button></div>{p.notice&&<div className="notice">{p.notice}</div>}</div><div className="hero-visual"><div className="orb"/><div className="hero-card glass"><Cloud/><b>My Cloud</b><span>Private. Organized. Yours.</span></div></div></section><section className="features"><Feature icon={<ImageIcon/>} title="Photos & Videos" text="Keep your memories in one secure place."/><Feature icon={<Folder/>} title="Folders & Albums" text="Organize files the way you want."/><Feature icon={<ShieldCheck/>} title="Private by default" text="Your account controls your files."/></section></main>{p.authMode!=='landing'&&<EmailModal mode={p.authMode} close={()=>p.setAuthMode('landing')}/>}</div>}
function EmailModal({mode,close}){const[e,setE]=useState(''),[pw,setPw]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');async function submit(x){x.preventDefault();if(!supabase)return;setBusy(true);const r=mode==='signup'?await supabase.auth.signUp({email:e,password:pw}):await supabase.auth.signInWithPassword({email:e,password:pw});setMsg(r.error?.message||(mode==='signup'?'Account created. Check your email if confirmation is enabled.':'Signed in.'));setBusy(false)}return <div className="modal"><div className="backdrop" onClick={close}/><div className="modal-card"><button className="close" onClick={close}><X/></button><div className="modal-logo"><Cloud/></div><h2>{mode==='signup'?'Create your account':'Welcome back'}</h2><p>Use your My Cloud account.</p><form onSubmit={submit}><input type="email" placeholder="Email address" value={e} onChange={x=>setE(x.target.value)} required/><input type="password" placeholder="Password" value={pw} onChange={x=>setPw(x.target.value)} minLength="6" required/><button className="primary-btn" disabled={busy}>{busy?'Please wait…':mode==='signup'?'Create account':'Sign in'}</button></form>{msg&&<div className="notice">{msg}</div>}</div></div>}

function Dashboard(p){const title={home:'Home',photos:'Photos',videos:'Videos',folders:'Folders',albums:'Albums',favorites:'Favorites',shared:'Shared',trash:'Trash',settings:'Settings'}[p.page]||'Home';const visible=useMemo(()=>{let a=p.files.filter(f=>!f.is_trashed);if(p.page==='trash')a=p.files.filter(f=>f.is_trashed);if(p.page==='photos')a=a.filter(f=>f.kind==='photo');if(p.page==='videos')a=a.filter(f=>f.kind==='video');if(p.page==='favorites')a=a.filter(f=>f.is_favorite);if(p.page==='folders'&&p.currentFolder)a=a.filter(f=>f.folder_id===p.currentFolder.id);if(p.page==='albums'&&p.selectedAlbum)a=a.filter(f=>f.album_id===p.selectedAlbum.id);if(p.search.trim())a=a.filter(f=>f.name.toLowerCase().includes(p.search.toLowerCase()));return a},[p.files,p.page,p.currentFolder,p.selectedAlbum,p.search]);const usage=p.files.filter(f=>!f.is_trashed).reduce((s,f)=>s+Number(f.size_bytes||0),0);return <div className="dashboard"><Sidebar {...p}/><main className="dash-content"><header className="dashbar"><button className="mobile-menu" onClick={()=>p.setMobileOpen(true)}><Menu/></button><div className="dash-search"><Search/><input placeholder="Search your cloud…" value={p.search} onChange={e=>p.setSearch(e.target.value)}/></div><ThemeToggle {...p}/><div className="avatar">{(p.profile?.display_name||p.session.user.email||'U').slice(0,1).toUpperCase()}</div></header><section className="dash-page">{p.notice&&<div className="notice">{p.notice}</div>}<div className="page-title"><div><small>MY CLOUD</small><h1>{title}</h1></div>{['home','photos','videos','folders','albums'].includes(p.page)&&<label className="upload-btn"><Upload/>{p.uploading?'Uploading…':'Upload'}<input type="file" multiple onChange={e=>p.uploadFiles(e.target.files)} disabled={p.uploading}/></label>}</div><Usage usage={usage}/>{p.page==='folders'?<FolderView {...p}/>:p.page==='albums'?<AlbumView {...p}/>:p.page==='settings'?<SettingsView {...p}/>:<><div className="quick-grid"><Quick icon={<ImageIcon/>} name="Photos" count={p.files.filter(f=>!f.is_trashed&&f.kind==='photo').length} go={()=>p.setPage('photos')}/><Quick icon={<Video/>} name="Videos" count={p.files.filter(f=>!f.is_trashed&&f.kind==='video').length} go={()=>p.setPage('videos')}/><Quick icon={<Folder/>} name="Folders" count={p.folders.length} go={()=>p.setPage('folders')}/><Quick icon={<Star/>} name="Favorites" count={p.files.filter(f=>!f.is_trashed&&f.is_favorite).length} go={()=>p.setPage('favorites')}/></div><div className="recent-head"><h2>{p.page==='trash'?'Recently deleted':'Files'}</h2><span>{visible.length} items</span></div>{p.loading?<div className="empty"><RefreshCw className="spin"/><b>Loading…</b></div>:visible.length?<div className="file-grid">{visible.map(f=><FileCard key={f.id} item={f} {...p}/>)}</div>:<div className="empty"><Cloud/><b>No files here</b><span>Upload something to get started.</span></div>}</>}</section></main></div>}
function Sidebar(p){const nav=[['home','Home',<HardDrive/>],['photos','Photos',<ImageIcon/>],['videos','Videos',<Video/>],['folders','Folders',<Folder/>],['albums','Albums',<Album/>],['favorites','Favorites',<Star/>],['shared','Shared',<Share2/>],['trash','Trash',<Trash2/>]];return <aside className={`sidebar ${p.mobileOpen?'open':''}`}><div className="side-head"><Brand/><button className="close mobile-only" onClick={()=>p.setMobileOpen(false)}><X/></button></div><nav>{nav.map(([id,label,icon])=><Nav key={id} icon={icon} label={label} active={p.page===id} go={()=>{p.setPage(id);p.setMobileOpen(false)}}/>)}</nav><div className="side-bottom"><Nav icon={<Settings/>} label="Settings" active={p.page==='settings'} go={()=>{p.setPage('settings');p.setMobileOpen(false)}}/><button className="nav" onClick={p.signOut}><LogOut/><span>Sign out</span></button></div></aside>}
function Usage({usage}){const gb=(usage/1024**3).toFixed(2),pct=Math.min(100,usage/TB*100);return <div className="usage-card glass"><div className="usage-head"><div><span>Storage used</span><b>{gb} GB of 1 TB</b></div><Cloud/></div><div className="progress"><i style={{width:`${pct}%`}}/></div><small>{(1024-gb*1).toFixed(2)} GB displayed remaining</small></div>}
function FolderView(p){const children=p.folders.filter(f=>(f.parent_id||null)===(p.currentFolder?.id||null));return <><div className="toolbar"><button className="primary-btn small" onClick={()=>{const n=prompt('Folder name');if(n)p.createFolder(n)}}><FolderPlus/> New folder</button>{p.currentFolder&&<button className="secondary-btn" onClick={()=>p.setCurrentFolder(null)}><ArrowLeft/> All folders</button>}</div>{p.currentFolder&&<div className="breadcrumb"><Folder/> {p.currentFolder.name}</div>}<div className="folder-grid">{children.map(f=><div className="folder-card" key={f.id} onDoubleClick={()=>p.setCurrentFolder(f)}><Folder/><b>{f.name}</b><div><button onClick={()=>p.renameFolder(f)}>Rename</button><button onClick={()=>p.deleteFolder(f)}>Delete</button></div></div>)}</div>{p.currentFolder&&<FileSection {...p} />}</>}
function AlbumView(p){return <><div className="toolbar"><button className="primary-btn small" onClick={()=>{const n=prompt('Album name');if(n)p.createAlbum(n)}}><Plus/> New album</button>{p.selectedAlbum&&<button className="secondary-btn" onClick={()=>p.setSelectedAlbum(null)}><ArrowLeft/> All albums</button>}</div>{p.selectedAlbum?<><div className="breadcrumb"><Album/> {p.selectedAlbum.name}</div><FileSection {...p}/></>:<div className="folder-grid">{p.albums.map(a=><div className="folder-card" key={a.id} onDoubleClick={()=>p.setSelectedAlbum(a)}><Album/><b>{a.name}</b><div><button onClick={()=>p.renameAlbum(a)}>Rename</button><button onClick={()=>p.deleteAlbum(a)}>Delete</button></div></div>)}</div>}</>}
function FileSection(p){const fs=p.files.filter(f=>!f.is_trashed&&((p.page==='folders'?(f.folder_id===p.currentFolder?.id):(f.album_id===p.selectedAlbum?.id))));return <div className="file-grid section-files">{fs.map(f=><FileCard key={f.id} item={f} {...p}/>)}</div>}
function FileCard(p){const{item}=p;const[url,setUrl]=useState('');useEffect(()=>{let live=true;if(supabase&&item.mime_type?.startsWith('image/'))supabase.storage.from('user-files').createSignedUrl(item.storage_path,300).then(({data})=>live&&setUrl(data?.signedUrl||''));return()=>{live=false}},[item]);return <article className="file-card"><div className="thumb">{url?<img src={url} alt={item.name}/>:item.kind==='video'?<Video/>:<ImageIcon/>}<span className="kind-badge">{item.kind}</span></div><div className="file-meta"><b title={item.name}>{item.name}</b><small>{(Number(item.size_bytes)/1024/1024).toFixed(1)} MB</small></div><div className="file-actions"><button onClick={()=>p.toggleFavorite(item)} title="Favorite"><Star fill={item.is_favorite?'currentColor':'none'}/></button><button onClick={()=>p.download(item)} title="Download"><Download/></button><button onClick={()=>p.share(item)} title="Share"><Share2/></button>{item.is_trashed?<><button onClick={()=>p.restore(item)} title="Restore">↶</button><button onClick={()=>p.forever(item)} title="Delete permanently"><X/></button></>:<button onClick={()=>p.trash(item)} title="Trash"><Trash2/></button>}<MoveMenu item={item} folders={p.folders} move={p.moveToFolder}/></div></article>}
function MoveMenu({item,folders,move}){const[open,setOpen]=useState(false);return <div className="move-wrap"><button onClick={()=>setOpen(!open)}><MoreVertical/></button>{open&&<div className="menu"><button onClick={()=>{move(item,null);setOpen(false)}}>Root</button>{folders.map(f=><button key={f.id} onClick={()=>{move(item,f.id);setOpen(false)}}>{f.name}</button>)}</div>}</div>}
function SettingsView(p){const[name,setName]=useState(p.profile?.display_name||'');const[avatar,setAvatar]=useState(p.profile?.avatar_url||'');const[pw,setPw]=useState('');return <div className="settings-grid"><section className="settings-card glass"><User/><h2>Profile</h2><label>Display name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Avatar URL<input value={avatar} onChange={e=>setAvatar(e.target.value)}/></label><label>Email<input value={p.session.user.email||''} disabled/></label><button className="primary-btn" onClick={()=>p.saveProfile({display_name:name,avatar_url:avatar})}><Save/> Save profile</button></section><section className="settings-card glass"><Palette/><h2>Background</h2><p>Choose the look of your My Cloud workspace.</p><div className="theme-grid">{BG_THEMES.map(t=><button key={t.id} className={`bg-choice ${p.background===t.id?'selected':''} ${t.className}`} onClick={()=>p.setBackground(t.id)}><span>{t.name}</span>{p.background===t.id&&<Check/>}</button>)}</div><div className="theme-row"><button className="secondary-btn" onClick={()=>p.setTheme(p.theme==='light'?'dark':'light')}>{p.theme==='light'?<Moon/>:<Sun/>} Toggle light/dark</button></div></section><section className="settings-card glass"><KeyRound/><h2>Password</h2><p>Change your account password.</p><input type="password" placeholder="New password" value={pw} onChange={e=>setPw(e.target.value)} minLength="6"/><button className="primary-btn" onClick={()=>{if(pw.length>=6){p.changePassword(pw);setPw('')}}}>Update password</button></section><section className="settings-card glass"><ShieldCheck/><h2>Account</h2><p>Your account is private by default. Storage quota is currently configured as 1 TB in the application.</p><button className="secondary-btn" onClick={p.signOut}><LogOut/> Sign out</button></section></div>}
function Feature({icon,title,text}){return <article className="feature"><div>{icon}</div><h3>{title}</h3><p>{text}</p></article>}
function Quick({icon,name,count,go}){return <button className="quick" onClick={go}><span>{icon}</span><b>{name}</b><small>{count} items</small></button>}
function Nav({icon,label,active,go}){return <button className={`nav ${active?'active':''}`} onClick={go}>{icon}<span>{label}</span></button>}
function Brand(){return <a className="brand" href="#"><span className="brand-mark"><Cloud/></span><span>My <strong>Cloud</strong></span></a>}
function ThemeToggle({theme,setTheme}){return <button className="theme-toggle" onClick={()=>setTheme(theme==='light'?'dark':'light')} aria-label="Toggle theme">{theme==='light'?<Sun/>:<Moon/>}</button>}
createRoot(document.getElementById('root')).render(<App/>)
